import type { ExperienceTypeSpec } from "../types.js";

/**
 * 경험 유형별 전용 항목 — 총 18종.
 * ARC 문서 '경험 유형별 입력 항목 정리'와 1:1 대응.
 * 각 유형은 공통 항목(기본 정보 6 + 확장 입력 8)을 기본 포함하고,
 * 아래 fields가 전용 항목으로 추가된다.
 */
export const EXPERIENCE_TYPES: readonly ExperienceTypeSpec[] = [
  /* ══════════════════ 🎓 학업 ══════════════════ */
  {
    id: "academic.major_course",
    category: "academic",
    label: "전공 및 수강 수업",
    emoji: "🎓",
    aliases: ["전공", "수강", "수업", "강의", "학점", "성적표", "커리큘럼"],
    signals: ["성적증명서", "수강신청 내역", "강의계획서", "학기 성적", "교수님", "과제 제출물"],
    fields: [
      { key: "schoolName", label: "학교명", kind: "text", required: true, group: "학교 정보" },
      { key: "major", label: "전공", kind: "text", group: "학교 정보" },
      { key: "enrollmentStatus", label: "재학/졸업 상태", kind: "select", options: ["재학중", "졸업", "휴학중", "졸업예정"], group: "학교 정보" },
      { key: "admissionDate", label: "입학일", kind: "date", group: "학교 정보" },
      { key: "graduationDate", label: "졸업(예정)일", kind: "date", group: "학교 정보" },
      { key: "transcript", label: "전체 학기 성적표", kind: "file", group: "학교 정보" },
      {
        key: "courses", label: "수업 기록", kind: "repeater", group: "수업 기록",
        hint: "수업 하나당 항목 1개. 과목이 여러 개면 전부 나눠서 넣을 것.",
        fields: [
          { key: "courseName", label: "수업명", kind: "text", required: true },
          { key: "professor", label: "교수", kind: "text" },
          { key: "department", label: "담당 전공 학과", kind: "text" },
          { key: "semester", label: "수강 학기/연도", kind: "text", required: true },
          { key: "grade", label: "취득 성적", kind: "text" },
          { key: "courseSummary", label: "수업 요약", kind: "longtext" },
          { key: "keyOutcome", label: "핵심 성과 기록", kind: "longtext" },
          { key: "teamProject", label: "팀프로젝트/과제 내용", kind: "longtext" },
        ],
      },
      { key: "careerImpact", label: "커리어에 준 영향", kind: "tags", group: "수업 기록" },
    ],
  },
  {
    id: "academic.society",
    category: "academic",
    label: "학회",
    emoji: "📚",
    aliases: ["학회", "학술단체", "학술동아리", "세미나 조직"],
    signals: ["학회 활동 인증서", "학술대회", "세미나 발표", "학회장", "기수"],
    fields: [
      { key: "societyName", label: "학회명", kind: "text", required: true, group: "학회 정보" },
      { key: "societyIntro", label: "학회 소개", kind: "longtext", group: "학회 정보" },
      { key: "officialUrl", label: "공식 URL/웹사이트", kind: "link", group: "학회 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "학회 정보", supersedes: ["period"] },
      { key: "certificate", label: "활동 인증서", kind: "file", group: "학회 정보" },
      { key: "motivation", label: "지원 동기", kind: "longtext", group: "학회 정보" },
      { key: "role", label: "역할/직책", kind: "text", required: true, group: "학회 정보", supersedes: ["myRole"] },
      {
        key: "projects", label: "프로젝트/연구활동", kind: "repeater", group: "프로젝트/연구활동 기록",
        fields: [
          { key: "name", label: "프로젝트/연구활동명", kind: "text", required: true },
          { key: "detailPeriod", label: "세부 기간", kind: "text", required: true },
          { key: "role", label: "직책/역할", kind: "text", required: true },
          { key: "goal", label: "연구/프로젝트 목표", kind: "longtext" },
          { key: "whatIDid", label: "내가 한 일", kind: "longtext" },
          { key: "keyOutcome", label: "핵심 성과", kind: "longtext" },
          { key: "presentation", label: "발표/포스터/세미나 여부", kind: "text" },
          { key: "feedback", label: "피드백/질문과 대응", kind: "longtext" },
        ],
      },
    ],
  },
  {
    id: "academic.club",
    category: "academic",
    label: "동아리/교내 단체",
    emoji: "👥",
    aliases: ["동아리", "교내 단체", "학생회", "중앙동아리", "소모임"],
    signals: ["동아리 활동 인증서", "총무", "회장", "운영진", "정기 모임", "MT", "학과 행사"],
    fields: [
      { key: "clubName", label: "동아리/단체명", kind: "text", required: true, group: "동아리/단체 정보" },
      { key: "clubIntro", label: "단체 소개", kind: "longtext", group: "동아리/단체 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "동아리/단체 정보", supersedes: ["period"] },
      { key: "certificate", label: "활동 인증서/수료 증빙", kind: "file", group: "동아리/단체 정보" },
      { key: "role", label: "직책/역할", kind: "text", required: true, group: "동아리/단체 정보", supersedes: ["myRole"] },
      {
        key: "activities", label: "활동 기록", kind: "repeater", group: "활동 기록",
        fields: [
          { key: "activityName", label: "활동명", kind: "text", required: true },
          { key: "detailPeriod", label: "세부 기간", kind: "text" },
          { key: "role", label: "직책/역할", kind: "text" },
          { key: "detail", label: "활동내용 상세", kind: "longtext" },
          { key: "result", label: "행사/운영 성과", kind: "longtext" },
        ],
      },
    ],
  },
  {
    id: "academic.research",
    category: "academic",
    label: "연구 경험/논문",
    emoji: "🔬",
    aliases: ["연구", "논문", "학부연구생", "RA", "랩", "학술지", "저널", "포스터"],
    signals: ["초록", "Abstract", "IRB", "실험 설계", "선행연구", "참고문헌", "게재", "peer review"],
    fields: [
      { key: "researchTitle", label: "연구 주제/논문 제목", kind: "text", required: true, group: "연구 정보" },
      { key: "affiliation", label: "소속/기관/랩", kind: "text", group: "연구 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "연구 정보", supersedes: ["period"] },
      { key: "role", label: "역할", kind: "select", options: ["주저자", "공저", "연구원", "RA", "기타"], group: "연구 정보" },
      { key: "researchQuestion", label: "연구 질문/가설", kind: "longtext", group: "연구 정보" },
      { key: "method", label: "방법/설계", kind: "longtext", group: "연구 정보" },
      { key: "dataSource", label: "데이터/자료 출처", kind: "text", group: "연구 정보" },
      { key: "myPart", label: "내가 맡은 파트", kind: "longtext", required: true, group: "연구 정보", supersedes: ["myRole"] },
      { key: "resultSummary", label: "결과 요약", kind: "longtext", group: "연구 정보" },
      { key: "achievements", label: "성과", kind: "tags", group: "연구 정보", supersedes: ["keyAchievement"] },
      { key: "shareLink", label: "재현/공유 자료", kind: "link", group: "연구 정보" },
      { key: "references", label: "참고문헌/관련 읽을거리", kind: "longtext", group: "연구 정보" },
      { key: "artifacts", label: "산출물", kind: "file", group: "연구 정보", supersedes: ["evidence"] },
    ],
  },

  /* ══════════════════ 💼 커리어 ══════════════════ */
  {
    id: "career.work",
    category: "career",
    label: "인턴 및 업무 경력",
    emoji: "💼",
    aliases: ["인턴", "근무", "재직", "회사", "업무", "경력", "직무", "정규직", "계약직", "프리랜서"],
    signals: ["경력증명서", "재직증명서", "근로계약", "온보딩", "스프린트", "JIRA", "회고 문서", "퇴사"],
    fields: [
      { key: "companyName", label: "회사명", kind: "text", required: true, group: "근무 정보" },
      { key: "employmentPeriod", label: "재직기간", kind: "daterange", required: true, group: "근무 정보", supersedes: ["period"] },
      { key: "employmentType", label: "고용 형태", kind: "select", options: ["인턴", "계약직", "정규직", "프리랜서"], group: "근무 정보" },
      { key: "position", label: "직책/직급", kind: "text", required: true, group: "근무 정보" },
      { key: "jobFunction", label: "직무(업무분야)", kind: "text", required: true, group: "근무 정보" },
      { key: "salary", label: "급여", kind: "text", group: "근무 정보", hint: "원문에 명시된 경우에만. 추정 금지." },
      { key: "motivation", label: "지원 동기", kind: "longtext", group: "근무 정보" },
      { key: "team", label: "팀/조직", kind: "text", group: "근무 정보", supersedes: ["team"] },
      { key: "workMode", label: "근무 형태", kind: "select", options: ["재택", "출근", "혼합"], group: "근무 정보" },
      {
        key: "tasks", label: "업무내용", kind: "repeater", group: "업무내용 기록",
        hint: "담당한 프로젝트/업무 단위로 쪼갤 것. 하나의 긴 문단으로 뭉치지 말 것.",
        fields: [
          { key: "name", label: "프로젝트/업무명", kind: "text", required: true },
          { key: "detailPeriod", label: "세부 기간", kind: "text" },
          { key: "role", label: "역할", kind: "text", required: true },
          { key: "detail", label: "업무내용 상세", kind: "longtext" },
          { key: "tools", label: "활용 툴", kind: "text" },
          { key: "collaborators", label: "협업 대상", kind: "text" },
          { key: "metrics", label: "성과 지표", kind: "longtext" },
          { key: "risks", label: "리스크/이슈 및 대응", kind: "longtext" },
        ],
      },
      { key: "resignReason", label: "퇴사 사유", kind: "longtext", group: "업무내용 기록" },
    ],
  },
  {
    id: "career.external",
    category: "career",
    label: "대외활동",
    emoji: "📣",
    aliases: ["대외활동", "서포터즈", "앰배서더", "기자단", "인턴십 프로그램", "부트캠프", "멘토링"],
    signals: ["활동 인증서", "위촉장", "OT", "미션 수행", "주최", "운영사무국"],
    fields: [
      { key: "activityName", label: "활동명", kind: "text", required: true, group: "활동 정보" },
      { key: "organizer", label: "주최/기관명", kind: "text", group: "활동 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "활동 정보", supersedes: ["period"] },
      { key: "certificate", label: "활동 인증서", kind: "file", group: "활동 정보" },
      { key: "role", label: "직책/역할", kind: "text", required: true, group: "활동 정보", supersedes: ["myRole"] },
      { key: "motivation", label: "지원 동기", kind: "longtext", group: "활동 정보" },
      { key: "mission", label: "담당 업무/미션", kind: "longtext", group: "활동내용 상세" },
      {
        key: "whatIDid", label: "내가 한 일", kind: "repeater", group: "활동내용 상세",
        fields: [{ key: "action", label: "행동", kind: "longtext" }],
      },
      { key: "collaboration", label: "협업/커뮤니케이션 방식", kind: "longtext", group: "활동내용 상세", supersedes: ["team"] },
      {
        key: "results", label: "결과/성과", kind: "repeater", group: "활동내용 상세", supersedes: ["keyAchievement", "outcome"],
        fields: [
          { key: "type", label: "성과 유형", kind: "text" },
          { key: "value", label: "수치", kind: "text", hint: "원문에 있는 숫자만. 없으면 비울 것." },
          { key: "desc", label: "설명", kind: "longtext" },
        ],
      },
      { key: "outputFile", label: "결과물/작업물", kind: "file", group: "활동내용 상세" },
      { key: "reference", label: "추천인/증언", kind: "text", group: "활동내용 상세" },
    ],
  },
  {
    id: "career.award",
    category: "career",
    label: "수상 경력",
    emoji: "🏆",
    aliases: ["수상", "공모전", "해커톤", "경진대회", "대회", "장학금", "표창"],
    signals: ["상장", "수상 내역", "대상", "최우수상", "우수상", "장려상", "심사평", "본선", "결선"],
    fields: [
      { key: "awardName", label: "수상명", kind: "text", required: true, group: "수상 정보" },
      { key: "organizer", label: "주최/기관", kind: "text", required: true, group: "수상 정보" },
      { key: "awardDate", label: "수상일", kind: "date", group: "수상 정보" },
      { key: "competitionName", label: "대회/프로그램명", kind: "text", group: "수상 정보" },
      { key: "awardRank", label: "수상 구분", kind: "select", options: ["대상", "최우수", "우수", "장려", "기타"], group: "수상 정보" },
      { key: "participationType", label: "참가 형태", kind: "select", options: ["개인", "팀"], group: "수상 정보" },
      { key: "teamMembers", label: "팀명/팀원", kind: "text", group: "수상 정보", supersedes: ["team"] },
      { key: "criteria", label: "평가 기준/요구사항", kind: "longtext", group: "수상 정보" },
      { key: "myContribution", label: "내 역할/기여", kind: "longtext", required: true, group: "수상 정보", supersedes: ["myRole"] },
      { key: "submission", label: "제출물/발표 자료", kind: "file", group: "수상 정보" },
      { key: "awardEvidence", label: "수상 증빙", kind: "file", group: "수상 정보", supersedes: ["evidence"] },
      { key: "keyAchievement", label: "핵심 성과", kind: "longtext", group: "수상 정보", supersedes: ["keyAchievement"] },
      { key: "competencyTags", label: "이 수상이 의미하는 역량", kind: "tags", group: "수상 정보" },
    ],
  },
  {
    id: "career.certificate",
    category: "career",
    label: "보유 자격증",
    emoji: "✅",
    aliases: ["자격증", "면허", "인증", "certification", "기사", "산업기사", "컴활", "정보처리"],
    signals: ["합격증", "자격증 번호", "발급기관", "취득일", "유효기간", "갱신"],
    fields: [
      { key: "certName", label: "자격증명", kind: "text", required: true, group: "자격증 정보" },
      { key: "issuer", label: "발급 기관", kind: "text", required: true, group: "자격증 정보" },
      { key: "acquiredDate", label: "취득일", kind: "date", group: "자격증 정보" },
      { key: "validity", label: "유효기간/갱신 필요 여부", kind: "text", group: "자격증 정보" },
      { key: "certNumber", label: "자격 번호", kind: "text", group: "자격증 정보" },
      { key: "gradeScore", label: "성적/등급", kind: "text", group: "자격증 정보" },
      { key: "prepPeriod", label: "준비 기간", kind: "daterange", group: "자격증 정보", supersedes: ["period"] },
      { key: "studyMethod", label: "학습 방식", kind: "select", options: ["강의", "독학", "스터디", "부트캠프"], group: "자격증 정보" },
      { key: "studyMaterials", label: "핵심 공부 자료", kind: "link", group: "자격증 정보" },
      {
        key: "applications", label: "실무 적용 사례", kind: "repeater", group: "실무 적용 사례",
        fields: [
          { key: "context", label: "적용 상황/프로젝트명", kind: "text", required: true },
          { key: "whatIDid", label: "내가 한 일", kind: "longtext" },
          { key: "effect", label: "결과/효과", kind: "longtext" },
        ],
      },
      { key: "certEvidence", label: "자격증 증빙", kind: "file", group: "실무 적용 사례", supersedes: ["evidence"] },
    ],
  },
  {
    id: "career.language",
    category: "career",
    label: "어학 능력",
    emoji: "🗣",
    aliases: ["어학", "토익", "토플", "OPIc", "JLPT", "HSK", "TOEIC", "IELTS", "회화"],
    signals: ["성적표", "점수", "등급", "응시일", "유효기간", "말하기 평가"],
    fields: [
      { key: "language", label: "언어", kind: "text", required: true, group: "어학 정보" },
      { key: "testName", label: "시험/인증명", kind: "text", group: "어학 정보" },
      { key: "score", label: "점수/등급", kind: "text", group: "어학 정보" },
      { key: "testDate", label: "응시일", kind: "date", group: "어학 정보" },
      { key: "validity", label: "유효기간", kind: "text", group: "어학 정보" },
      { key: "strengths", label: "강점 영역", kind: "checklist", options: ["듣기", "읽기", "말하기", "쓰기"], group: "어학 정보" },
      { key: "studyPeriod", label: "학습 기간", kind: "daterange", group: "어학 정보", supersedes: ["period"] },
      { key: "studyMethod", label: "학습 방식", kind: "select", options: ["학원", "독학", "회화", "첨삭", "스터디"], group: "어학 정보" },
      {
        key: "usages", label: "활용 사례", kind: "repeater", group: "실제 활용 사례",
        fields: [
          { key: "situation", label: "상황", kind: "text", required: true },
          { key: "myRole", label: "내가 한 역할", kind: "longtext" },
          { key: "difficulty", label: "어려웠던 점과 해결", kind: "longtext" },
          { key: "result", label: "결과", kind: "longtext" },
        ],
      },
    ],
  },

  /* ══════════════════ 🚀 프로젝트 ══════════════════ */
  {
    id: "project.personal",
    category: "project",
    label: "개인 프로젝트",
    emoji: "🚀",
    aliases: ["개인 프로젝트", "토이 프로젝트", "사이드 프로젝트", "1인 개발", "혼자 만든"],
    signals: ["README", "커밋 로그", "배포 링크", "기술 스택", "아키텍처 결정", "직접 기획"],
    fields: [
      { key: "projectName", label: "프로젝트명", kind: "text", required: true, group: "프로젝트 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "프로젝트 정보", supersedes: ["period"] },
      { key: "oneLiner", label: "한 줄 설명", kind: "text", required: true, group: "프로젝트 정보", supersedes: ["summary"] },
      { key: "goal", label: "목표/만들고 싶었던 이유", kind: "longtext", group: "프로젝트 정보", supersedes: ["background"] },
      { key: "targetUser", label: "대상 사용자/사용 상황", kind: "longtext", group: "프로젝트 정보" },
      { key: "features", label: "주요 기능", kind: "checklist", freeOptions: true, group: "프로젝트 정보", hint: "원문에 나열된 기능을 항목으로 분해." },
      { key: "techStack", label: "기술/도구", kind: "tags", group: "프로젝트 정보", supersedes: ["skills"] },
      {
        key: "decisions", label: "설계/결정", kind: "repeater", group: "설계/결정 기록",
        fields: [
          { key: "topic", label: "결정 주제", kind: "text", required: true },
          { key: "alternatives", label: "대안 비교", kind: "longtext" },
          { key: "reason", label: "선택 이유", kind: "longtext" },
          { key: "resultLearned", label: "결과/배운 점", kind: "longtext" },
        ],
      },
      { key: "outcome", label: "성과", kind: "longtext", group: "설계/결정 기록", supersedes: ["keyAchievement", "outcome"] },
      { key: "demoLink", label: "데모/배포 링크", kind: "link", group: "설계/결정 기록" },
      { key: "repoLink", label: "저장소 링크", kind: "link", group: "설계/결정 기록" },
      { key: "screenshots", label: "스크린샷/영상", kind: "file", group: "설계/결정 기록" },
      { key: "nextPlan", label: "다음 개선 계획", kind: "longtext", group: "설계/결정 기록" },
    ],
  },
  {
    id: "project.team",
    category: "project",
    label: "팀 프로젝트",
    emoji: "👨‍👩‍👧‍👦",
    aliases: ["팀 프로젝트", "협업 프로젝트", "조별과제", "해커톤 팀", "스터디 프로젝트"],
    signals: ["역할 분담", "스크럼", "PR 리뷰", "팀원", "회고", "컨플릭트", "일정 조율"],
    fields: [
      { key: "projectName", label: "프로젝트명", kind: "text", required: true, group: "프로젝트 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "프로젝트 정보", supersedes: ["period"] },
      { key: "teamComposition", label: "팀 구성", kind: "longtext", group: "프로젝트 정보", supersedes: ["team"] },
      { key: "myRole", label: "내 역할", kind: "longtext", required: true, group: "프로젝트 정보", supersedes: ["myRole"] },
      { key: "problemDefinition", label: "목표/문제 정의", kind: "longtext", group: "프로젝트 정보", supersedes: ["background"] },
      { key: "collaboration", label: "협업 방식", kind: "longtext", group: "프로젝트 정보" },
      { key: "roleMatrix", label: "역할 분담표", kind: "longtext", group: "프로젝트 정보" },
      {
        key: "workLogs", label: "작업 기록", kind: "repeater", group: "작업 기록",
        hint: "'내가' 한 작업 단위로. 팀 전체 작업을 내 것으로 적지 말 것.",
        fields: [
          { key: "name", label: "작업/이슈명", kind: "text", required: true },
          { key: "period", label: "기간", kind: "text" },
          { key: "whatIDid", label: "내가 한 일", kind: "longtext", required: true },
          { key: "result", label: "결과", kind: "longtext" },
        ],
      },
      { key: "conflictResolution", label: "갈등/의견 차이와 조율", kind: "longtext", group: "작업 기록" },
      { key: "outputLink", label: "결과물 링크", kind: "link", group: "작업 기록" },
      { key: "retrospective", label: "회고 (잘된 점/아쉬운 점/다음엔)", kind: "longtext", group: "작업 기록", supersedes: ["learned"] },
    ],
  },
  {
    id: "project.creative",
    category: "project",
    label: "창작물/작업물",
    emoji: "🎨",
    aliases: ["창작물", "작업물", "포트폴리오", "디자인", "영상", "음악", "사진", "일러스트", "글"],
    signals: ["작품", "레퍼런스", "컨셉", "스토리보드", "썸네일", "보정", "믹싱", "연재"],
    fields: [
      { key: "workName", label: "작품/작업물명", kind: "text", required: true, group: "작품 정보" },
      { key: "field", label: "분야", kind: "select", options: ["디자인", "글", "영상", "음악", "사진", "일러스트", "기타"], group: "작품 정보" },
      { key: "productionPeriod", label: "제작 기간", kind: "daterange", group: "작품 정보", supersedes: ["period"] },
      { key: "oneLiner", label: "한 줄 소개", kind: "text", required: true, group: "작품 정보", supersedes: ["summary"] },
      { key: "intent", label: "의도/주제", kind: "longtext", group: "작품 정보", supersedes: ["background"] },
      { key: "tools", label: "사용 도구", kind: "tags", group: "작품 정보", supersedes: ["skills"] },
      {
        key: "process", label: "제작 과정", kind: "repeater", group: "제작 과정",
        fields: [
          { key: "stage", label: "단계명", kind: "text", required: true },
          { key: "whatIDid", label: "한 일", kind: "longtext" },
          { key: "decisions", label: "고민/결정", kind: "longtext" },
          { key: "result", label: "결과", kind: "longtext" },
        ],
      },
      { key: "publicLink", label: "공개 링크", kind: "link", group: "제작 과정" },
      { key: "reception", label: "반응/성과", kind: "longtext", group: "제작 과정", supersedes: ["outcome", "keyAchievement"] },
      { key: "copyright", label: "저작권/사용 범위", kind: "text", group: "제작 과정" },
    ],
  },

  /* ══════════════════ 🌱 개인성장 ══════════════════ */
  {
    id: "growth.volunteer",
    category: "growth",
    label: "봉사활동",
    emoji: "❤️",
    aliases: ["봉사", "자원봉사", "재능기부", "나눔", "캠페인"],
    signals: ["봉사 확인서", "1365", "VMS", "봉사시간", "수혜자", "복지관", "센터"],
    fields: [
      { key: "volunteerName", label: "봉사활동명", kind: "text", required: true, group: "봉사 정보" },
      { key: "organization", label: "기관/장소", kind: "text", group: "봉사 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "봉사 정보", supersedes: ["period"] },
      { key: "totalHours", label: "총 시간", kind: "text", group: "봉사 정보" },
      { key: "target", label: "대상", kind: "select", options: ["아동", "노인", "동물", "환경", "기타"], group: "봉사 정보" },
      { key: "activityType", label: "활동 형태", kind: "select", options: ["오프라인", "온라인", "기획", "현장"], group: "봉사 정보" },
      { key: "myRole", label: "내 역할", kind: "longtext", required: true, group: "봉사 정보", supersedes: ["myRole"] },
      { key: "activityDetail", label: "활동 내용", kind: "longtext", group: "봉사 정보" },
      { key: "impact", label: "임팩트/변화", kind: "longtext", group: "봉사 정보", supersedes: ["outcome", "keyAchievement"] },
      { key: "reflection", label: "느낀 점/가치관 변화", kind: "longtext", group: "봉사 정보", supersedes: ["learned"] },
      { key: "certificate", label: "봉사 확인서", kind: "file", group: "봉사 정보", supersedes: ["evidence"] },
    ],
  },
  {
    id: "growth.overseas",
    category: "growth",
    label: "해외 경험",
    emoji: "🌍",
    aliases: ["해외", "교환학생", "어학연수", "워홀", "해외 인턴", "배낭여행", "글로벌"],
    signals: ["비자", "출입국", "현지", "홈스테이", "기숙사", "환전", "항공권", "문화 차이"],
    fields: [
      { key: "experienceType", label: "경험 유형", kind: "select", options: ["교환학생", "연수", "여행", "해외 인턴", "기타"], group: "해외 경험 정보" },
      { key: "countryCity", label: "국가/도시", kind: "text", required: true, group: "해외 경험 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "해외 경험 정보", supersedes: ["period"] },
      { key: "purpose", label: "목적", kind: "longtext", group: "해외 경험 정보", supersedes: ["background"] },
      { key: "activitySummary", label: "활동 요약", kind: "longtext", required: true, group: "해외 경험 정보" },
      { key: "languageLevel", label: "언어 사용 수준", kind: "text", group: "해외 경험 정보" },
      {
        key: "challenges", label: "어려웠던 상황", kind: "repeater", group: "어려웠던 상황",
        fields: [
          { key: "situation", label: "상황", kind: "text", required: true },
          { key: "response", label: "내가 한 대응", kind: "longtext" },
          { key: "result", label: "결과", kind: "longtext" },
          { key: "learned", label: "배운 점", kind: "longtext" },
        ],
      },
      { key: "outcome", label: "성과/산출물", kind: "longtext", group: "어려웠던 상황", supersedes: ["outcome", "keyAchievement"] },
      { key: "evidence", label: "증빙", kind: "file", group: "어려웠던 상황", supersedes: ["evidence"] },
    ],
  },
  {
    id: "growth.fitness",
    category: "growth",
    label: "운동 및 신체 역량",
    emoji: "🏃",
    aliases: ["운동", "헬스", "러닝", "마라톤", "클라이밍", "수영", "구기", "체력", "다이어트"],
    signals: ["훈련 일지", "PB", "기록 단축", "체지방", "인바디", "대회 참가", "루틴"],
    fields: [
      { key: "sport", label: "종목", kind: "text", required: true, group: "운동 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "운동 정보", supersedes: ["period"] },
      { key: "goal", label: "목표", kind: "longtext", group: "운동 정보", supersedes: ["background"] },
      { key: "currentLevel", label: "현재 수준", kind: "text", group: "운동 정보" },
      { key: "trainingPlan", label: "훈련 계획", kind: "text", group: "운동 정보" },
      {
        key: "logs", label: "기록 로그", kind: "repeater", group: "기록 로그",
        hint: "날짜별 로그. 원문에 날짜가 여러 개면 각각 항목으로 분리.",
        fields: [
          { key: "date", label: "날짜", kind: "date", required: true },
          { key: "content", label: "훈련 내용", kind: "longtext", required: true },
          { key: "record", label: "기록", kind: "text" },
          { key: "condition", label: "컨디션/메모", kind: "longtext" },
        ],
      },
      { key: "competition", label: "대회/인증", kind: "longtext", group: "기록 로그" },
      { key: "change", label: "변화/성과", kind: "longtext", group: "기록 로그", supersedes: ["outcome", "keyAchievement"] },
      { key: "consistencyEvidence", label: "꾸준함 증거", kind: "file", group: "기록 로그", supersedes: ["evidence"] },
    ],
  },
  {
    id: "growth.reading",
    category: "growth",
    label: "독서",
    emoji: "📖",
    aliases: ["독서", "책", "완독", "서평", "독후감", "북클럽"],
    signals: ["저자", "출판사", "챕터", "밑줄", "인용", "발췌", "독서모임"],
    fields: [
      { key: "bookTitle", label: "도서명", kind: "text", required: true, group: "독서 정보" },
      { key: "author", label: "저자", kind: "text", group: "독서 정보" },
      { key: "readPeriod", label: "읽은 기간/완독일", kind: "text", group: "독서 정보", supersedes: ["period"] },
      { key: "reason", label: "읽은 이유", kind: "longtext", group: "독서 정보", supersedes: ["background"] },
      { key: "summary3", label: "핵심 요약 (3줄)", kind: "longtext", required: true, group: "독서 정보", hint: "정확히 3줄. 각 줄은 책의 주장 하나." },
      { key: "quotes", label: "인상 깊은 문장", kind: "longtext", group: "독서 정보" },
      {
        key: "applications", label: "적용/실험", kind: "repeater", group: "적용/실험",
        fields: [
          { key: "topic", label: "적용할 주제", kind: "text", required: true },
          { key: "action", label: "내가 한 행동", kind: "longtext" },
          { key: "result", label: "결과/느낌 점", kind: "longtext" },
        ],
      },
      { key: "relatedLink", label: "관련 자료", kind: "link", group: "적용/실험" },
      { key: "recommendTo", label: "추천 대상", kind: "text", group: "적용/실험" },
    ],
  },
  {
    id: "growth.journal",
    category: "growth",
    label: "기록 (일지/회고)",
    emoji: "🗒",
    aliases: ["일지", "회고", "저널", "다이어리", "주간 회고", "TIL", "일기"],
    signals: ["오늘", "이번 주", "KPT", "잘한 점", "아쉬운 점", "다음 액션", "루틴 점검"],
    fields: [
      { key: "topic", label: "기록 주제", kind: "text", required: true, group: "기록 정보" },
      { key: "recordDate", label: "기록 날짜", kind: "date", group: "기록 정보" },
      { key: "frequency", label: "기록 빈도", kind: "select", options: ["매일", "주1회", "월1회", "비정기"], group: "기록 정보" },
      { key: "trigger", label: "기록 트리거", kind: "longtext", group: "기록 정보" },
      { key: "whatIDid", label: "오늘/이번 주에 한 일", kind: "longtext", required: true, group: "기록 정보", supersedes: ["actions"] },
      { key: "didWell", label: "잘한 점 1개", kind: "longtext", group: "기록 정보", hint: "정확히 1개." },
      { key: "regret", label: "아쉬운 점 1개", kind: "longtext", group: "기록 정보", hint: "정확히 1개." },
      { key: "learned", label: "배운 점 1개", kind: "longtext", group: "기록 정보", supersedes: ["learned"], hint: "정확히 1개." },
      { key: "nextAction", label: "다음 행동 1개", kind: "longtext", group: "기록 정보", hint: "정확히 1개." },
      {
        key: "insights", label: "인사이트/패턴", kind: "repeater", group: "인사이트/패턴",
        fields: [
          { key: "pattern", label: "발견한 패턴", kind: "text", required: true },
          { key: "evidence", label: "근거", kind: "text" },
          { key: "behaviorChange", label: "바꿀 행동", kind: "longtext" },
        ],
      },
      { key: "attachment", label: "첨부", kind: "file", group: "인사이트/패턴", supersedes: ["evidence"] },
    ],
  },
  {
    id: "growth.goal",
    category: "growth",
    label: "목표/계획",
    emoji: "🎯",
    aliases: ["목표", "계획", "플랜", "로드맵", "OKR", "버킷리스트"],
    signals: ["마감일", "우선순위", "체크포인트", "달성", "진행률", "To-do", "성공 기준"],
    fields: [
      { key: "goalName", label: "목표명", kind: "text", required: true, group: "목표 정보" },
      { key: "period", label: "기간", kind: "daterange", required: true, group: "목표 정보", supersedes: ["period"] },
      { key: "goalType", label: "목표 유형", kind: "select", options: ["학습", "커리어", "건강", "프로젝트", "기타"], group: "목표 정보" },
      { key: "goalLevel", label: "목표 수준", kind: "select", options: ["상", "중", "하"], group: "목표 정보", supersedes: ["difficulty"] },
      { key: "successCriteria", label: "성공 기준", kind: "longtext", required: true, group: "목표 정보" },
      {
        key: "plans", label: "세부 계획", kind: "repeater", group: "세부 계획",
        fields: [
          { key: "task", label: "할 일", kind: "text", required: true },
          { key: "deadline", label: "마감일", kind: "date" },
          { key: "estimate", label: "예상 소요", kind: "text" },
          { key: "priority", label: "우선순위", kind: "text" },
          { key: "checkpoint", label: "체크포인트/측정 지표", kind: "longtext" },
        ],
      },
      {
        key: "progress", label: "진행 기록", kind: "repeater", group: "진행 기록",
        fields: [
          { key: "date", label: "날짜", kind: "date", required: true },
          { key: "content", label: "진행 내용", kind: "longtext", required: true },
          { key: "blockers", label: "막힌 점/리스크", kind: "longtext" },
          { key: "nextAction", label: "다음 액션", kind: "longtext" },
        ],
      },
      { key: "evidence", label: "증빙", kind: "file", group: "진행 기록", supersedes: ["evidence"] },
    ],
  },
] as const;

export const TYPE_BY_ID = new Map(EXPERIENCE_TYPES.map((t) => [t.id, t]));
export const TYPE_IDS = EXPERIENCE_TYPES.map((t) => t.id);
